[bot]

    [bot.general]
    codename = "Carbon"

    [bot.discord]
    appid = "" # replace with unquoted integer
    token = ""

    [bot.denylist]
        # Users unable to be parsed by the Spotify status / now playing command.
        #
        # Anyone in the denylist cannot have their current Spotify status checked
        # by the bot.
        [bot.denylist.spotify]
        ids = [ ]

    [bot.logging]
    enabled = true
    level = "info"

[api]

    [api.music]

        [api.music.spotify]
        client_id = ""
        client_secret = ""

        [api.music.lastfm]
        api_key = ""

    [api.entertainment]
    tmdb = ""

    [api.services]
    github = ""
    google = ""
